--CREATE TABLE





CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
GENDER CHAR(1),
Phone_Number NUMBER,
PRIMARY KEY(CUSTOMER_ID)
);


CREATE TABLE  TRANSACTIONS(	
TRANS_ID NUMBER, 
PAYMENT_METHOD VARCHAR(30), 
PAYMENT_DATE DATE, 
CUSTOMER_ID NUMBER, 
PRIMARY KEY(TRANS_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE ADDRESS(
STREET VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
COUNTRY VARCHAR(50),
CUSTOMER_ID NUMBER,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE BOOKING(
BOOKING_ID NUMBER,
BOOK_DATE DATE,
CUSTOMER_ID NUMBER,
PRIMARY KEY(BOOKING_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE RESERVATION(
RES_ID NUMBER,
CHECK_IN_DATE DATE,
CHECK_OUT_DATE DATE,
NO_OF_DAYS NUMBER,
CUSTOMER_ID NUMBER,
BOOKING_ID NUMBER,
PRIMARY KEY(RES_ID),
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

CREATE TABLE ROOM(
ROOM_NO NUMBER,
ROOM_TYPE VARCHAR(20),
ROOM_PRICE NUMBER,
CUSTOMER_ID NUMBER,
RES_ID NUMBER,
PRIMARY KEY(ROOM_NO),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (RES_ID) REFERENCES RESERVATION(RES_ID)
);
