--VIEW CODE



CREATE VIEW CUS_VIEW AS
SELECT CUSTOMER_ID, FIRST_NAME,LAST_NAME,PHONE_NUMBER, GENDER
FROM CUSTOMER;

SELECT * FROM CUS_VIEW;

DROP VIEW CUS_VIEW;



CREATE VIEW TRANS_VIEW AS
SELECT TRANS_ID,PAYMENT_METHOD,PAYMENT_DATE,CUSTOMER_ID
FROM TRANSACTIONS
WHERE (PAYMENT_METHOD = 'BANK' AND CUSTOMER_ID > 20220005);

SELECT * FROM TRANS_VIEW;

DROP VIEW TRANS_VIEW;



CREATE VIEW TRANS_VIEW_2 AS
SELECT TRANS_ID,PAYMENT_METHOD,PAYMENT_DATE,CUSTOMER_ID
FROM TRANSACTIONS
WHERE PAYMENT_METHOD = 'BKASH';

SELECT * FROM TRANS_VIEW_2;


UPDATE TRANS_VIEW_2
SET PAYMENT_METHOD = 'RRR', PAYMENT_DATE = '18-MAY-22'
WHERE TRANS_ID=202007;

SELECT * FROM TRANS_VIEW_2;


DELETE FROM TRANS_VIEW_2 WHERE CUSTOMER_ID = 20220004;

SELECT * FROM TRANS_VIEW_2;

DROP VIEW TRANS_VIEW_2;
